### ISSUE TITLE
[solved] Unable to resolve module typescript/2.9/node_modules

### ISSUE THREAD

**Issue by murray1337** [EvaCoop/eosjs-react-native#1]
Hi there,
thanks for this library! Hopefully it will be used in many RN EOS projects.

So I tried to install it in 1) this copied repo and 2) my app, and followed the instructions given.
Unfortunately in both cases  I get the following error.
I use Mac OS High Sierra, yarn 1.70, npm 6.20

`error: bundling failed: Error: Unable to resolve module `../Library/Caches/typescript/2.9/node_modules/@types/react` from `/Users/admin/EOSwallet/App.js`: The module `../Library/Caches/typescript/2.9/node_modules/@types/react` could not be found from `/Users/admin/EOSwallet/App.js`. Indeed, none of these files exist:`

![eoswallet](https://user-images.githubusercontent.com/26665436/43563338-030d2bf4-9622-11e8-96d2-2229c59f28d2.jpg)

The tips at the rn-nodeify repo did not help help. Trying to install typescript manually as well.

> rn-nodeify won't work with modules that are added using npm link.
modules that contain a .babelrc will cause problems with the latest react-native version (0.20 at this time), remove them after installation (rm node_modules/*/.babelrc)
when installing a package from git, the postinstall hook isn't triggered, run it manually instead (npm run postinstall)
restart the react-native packager after installing a module!
removing the packager cache helps as well sometimes (rm -fr $TMPDIR/react-*)
rn-nodeify currently uses npm to install shims. PRs are welcome to make it compatible with yarn

Gonna try last tip and let you know about the results:

> use npm@3. npm@5 has some issues that cause node_modules to disappear. See:

**Comment by murray1337** [comment]
using npm@3 did not work

**Comment by murray1337** [comment]
Fixed. Bug in VScode, although I was not even using Typescript

https://github.com/Microsoft/vscode/issues/52675

**Comment by raphaelgodro** [comment]
Seems like its been solved.
