### ISSUE TITLE
How to call eosio.token transfer

### ISSUE THREAD

**Issue by yankunsam** [EvaCoop/eosjs-react-native#3]
transferPara = {
    "from": 'eosio.token',
    "to": 'eosio',
    "quantity": '134.0000 EOS',
    "memo": 'by react native'
  };
  return net.transfer(transferPara).then(info => {
    return info;
  });

There is no error that reports, but the balance is the same. So is it okay for transaction?

**Comment by raphaelgodro** [comment]
It works exactly the same as eosjs if you added eosjs properly in your react-native project. Please note it doesn't work with `Expo` projects.

Look at `https://github.com/EvaCoop/eosjs-react-native/blob/master/EOS_example.js` to get a how-to import.
