### ISSUE TITLE
Adding to existing project isn't clear

### ISSUE THREAD

**Issue by dreson4** [EvaCoop/eosjs-react-native#4]
I don't understand your instructions at all when adding to existing project.
After installing react-native-secure-random what comes next?

> Following this, enable the crypto module in �./shim.js Change // require('crypto') to -> require('crypto')

Where does the `shim.js` file stay? In my local directory or in node_modules?

And then `hack_to_browser.sh` where does this one stay? 

I tried adding the files in my react-native project directory and everything broke I had to revert all the changes.

**Comment by raphaelgodro** [comment]
the shim.js file lives in the root directory of the project. You need to uncomment the line within it where there is `//require('crypto')` and change it to `require('crypto')`
