### ISSUE TITLE
help ^^ , eosjs unresponsive in android when "Debug JS Remotely" is disabled.

### ISSUE THREAD

**Issue by Kevinstone123** [EvaCoop/eosjs-react-native#5]
It works perfectly in ios, however, in andriod, "Debug JS Remotely" needs to stay enabled for eosjs to be responsive (I was trying to create a transaction (httpEndpoint is set to 'null' ), but no object was returned when "Debug JS Remotely" is disabled. )

Any ideas?

**Comment by Kevinstone123** [comment]
i has fixed this issue，
The simplest way to fix the issue

"(evaluating '_iterator2[typeof Symbol === "function" ? typeof Symbol === "function" ? Symbol.iterator : "@@iterator" : "@@iterator"]()')" 

error without any libraries is to do :

add this proly fill in your index.js

if (Platform.OS === 'android') {
  if (typeof Symbol === 'undefined') {
    if (Array.prototype['@@iterator'] === undefined) {
      Array.prototype['@@iterator'] = function() {
        let i = 0;
        return {
          next: () => ({
            done: i >= this.length,
            value: this[i++],
          }),
        };
      };
    }
  }
}

**Comment by raphaelgodro** [comment]
@Kevinstone123 : That's great! Can you do a pull requests? I never had this issue on Android, that's curious.
