### ISSUE TITLE
crypto and securerandom

### ISSUE THREAD

**Issue by murray1337** [EvaCoop/eosjs-react-native#8]
When following the instructions, `react-native-crypto` and `react-native-randombytes` are installed.

1)
I did not need to out comment the line `require('crypto')` , since it was never `//require('crypto')`
Is this normal? Is there any test I can do to check if randombytes is really used or is it atomic, it would just crash or work perfectly? Extremely important to know before using in production.

2)
> npm i --save react-native-securerandom

Is this lib used somewhere in the package? I could not find it except in the package.json. Is it necessary anyways, since react-native-randombytes is installed?

**Comment by raphaelgodro** [comment]
I updated the readme, those were indeed unnecessary libs. Just some steps i added while trying t find this solution and forgot to remove them.
