### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by DharaniRenu1** [EvaCoop/eosjs-react-native#9]
I ain't able to do with this and the file is not building while running 'react-native run-android'. I have tried both the ways of creating new and with existing one. Anyone here help to fix it.
Thanks in advance.

**Comment by raphaelgodro** [comment]
What is the received error? I know there are some issues with the current release of eosjs on Android prod environment.

**Comment by DharaniRenu1** [comment]
I cloned and make the commands. After adding,
subprojects {
   afterEvaluate {project ->
       if (project.hasProperty("android")) {
           android {
               compileSdkVersion 27
               buildToolsVersion '27.0.0'
           }
       }
   }
}
this commands in the build.gradle and ran the ./gradlew ...
At last, I got the result.
Thanks...
